-- ЕБЛ: схема боевой версии.
-- Единица данных — поход (visits + visit_players). Всё до запуска портала — «входящий остаток» из таблицы секретаря
-- (legacy_visits, legacy_standings). Итоговую таблицу пишет edge-функция recompute в standings.

-- ---------- участники и вход ----------
create table public.players (
  id uuid primary key default gen_random_uuid(),
  nick text not null unique,
  is_secretary boolean not null default false,
  joined_at date,
  left_at date,
  created_at timestamptz not null default now()
);

-- Telegram-аккаунты. Отдельно от players, чтобы telegram id не был виден всем.
create table public.player_accounts (
  id uuid primary key default gen_random_uuid(),
  player_id uuid references public.players(id) on delete cascade,
  tg_id bigint unique,
  tg_username text,
  tg_name text,
  auth_user uuid unique references auth.users(id) on delete set null,
  claimed_nick text,                 -- «это я» — ждёт подтверждения секретарём
  created_at timestamptz not null default now()
);
create index on public.player_accounts (lower(tg_username));

-- ---------- бани ----------
create table public.baths (
  id bigint generated by default as identity primary key,
  name text not null check (length(name) between 2 and 200),
  type text check (type in ('public', 'spa', 'private')),
  country text,
  region text,
  lat double precision,
  lng double precision,
  precision text check (precision in ('exact', 'city', 'region', 'country')),
  status text not null default 'ok' check (status in ('ok', 'pending', 'rejected')),
  created_by uuid references public.players(id),
  created_at timestamptz not null default now()
);

-- ---------- входящий остаток из таблицы секретаря ----------
-- походы по баням: 2023–2025 и 2026 до запуска (ники как в таблице; бывшие участники тоже тут)
create table public.legacy_visits (
  bath_id bigint not null references public.baths(id) on delete cascade,
  year int not null,
  nick text not null,
  n int not null check (n > 0),
  primary key (bath_id, year, nick)
);

-- общий и недельный зачёт 2026 до недели cutover_week
create table public.legacy_standings (
  nick text primary key,
  total numeric not null,
  baths int not null default 0,
  u int not null default 0, uu int not null default 0, long int not null default 0,
  k int not null default 0, pub int not null default 0, reg int not null default 0,
  week_pts jsonb not null default '{}',
  week_baths jsonb not null default '{}'
);

create table public.settings (
  key text primary key,
  value jsonb not null
);

-- ---------- журнал походов ----------
create table public.visits (
  id bigint generated by default as identity primary key,
  bath_id bigint not null references public.baths(id),
  entered_at timestamptz not null,
  posted_at timestamptz not null default now(),   -- по нему считается неделя (п. 6)
  duration_min int not null check (duration_min >= 60),
  status text not null default 'pending' check (status in ('pending', 'ok', 'rejected')),
  created_by uuid not null references public.players(id),
  moderated_by uuid references public.players(id),
  moderated_at timestamptz,
  reject_reason text,
  tg_link text,
  created_at timestamptz not null default now()
);
create index on public.visits (status, posted_at);
create index on public.visits (bath_id);

-- кто был в походе; долгий поход каждый подтверждает сам (п. 15)
create table public.visit_players (
  visit_id bigint not null references public.visits(id) on delete cascade,
  player_id uuid not null references public.players(id),
  has_proof boolean not null default false,
  photos text[] not null default '{}',
  primary key (visit_id, player_id)
);
create index on public.visit_players (player_id);

create table public.reviews (
  id bigint generated by default as identity primary key,
  bath_id bigint not null references public.baths(id) on delete cascade,
  player_id uuid not null references public.players(id),
  rating smallint not null check (rating between 1 and 5),
  text text not null check (length(text) between 1 and 2000),
  created_at timestamptz not null default now(),
  unique (bath_id, player_id)
);

-- итоговая таблица, её пишет edge-функция recompute
create table public.standings (
  nick text primary key,
  total numeric not null,
  baths int not null default 0,
  u int not null default 0, uu int not null default 0, long int not null default 0,
  k int not null default 0, pub int not null default 0, reg int not null default 0,
  week_pts jsonb not null default '{}',
  week_baths jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

-- очки по каждому походу (для ленты), пишет recompute
create table public.visit_points (
  visit_id bigint not null references public.visits(id) on delete cascade,
  nick text not null,
  total numeric not null,
  lines jsonb not null,
  primary key (visit_id, nick)
);

-- ---------- помощники для политик ----------
create function public.me() returns uuid
language sql stable security definer set search_path = public as $$
  select player_id from player_accounts where auth_user = auth.uid() and player_id is not null limit 1
$$;

create function public.is_secretary() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select is_secretary from players where id = public.me()), false)
$$;

-- «это я»: участник без привязки выбирает свой ник, секретарь подтверждает
create function public.claim_nick(p_nick text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from players where nick = p_nick) then
    raise exception 'Нет такого участника: %', p_nick;
  end if;
  update player_accounts set claimed_nick = p_nick where auth_user = auth.uid() and player_id is null;
end $$;

-- походы по баням/годам/участникам для карты и тепловой карты — та же детализация, что в таблице секретаря,
-- без дат и компаний. Представление работает с правами владельца: журнал походов закрыт политиками,
-- а эти агрегаты открыты всем.
create view public.bath_counts as
  select bath_id, year, nick, n from public.legacy_visits
  union all
  select v.bath_id, extract(year from v.entered_at at time zone 'Europe/Moscow')::int, p.nick, count(*)::int
  from public.visits v
  join public.visit_players vp on vp.visit_id = v.id
  join public.players p on p.id = vp.player_id
  where v.status = 'ok'
  group by 1, 2, 3;

-- ---------- политики ----------
alter table public.players enable row level security;
alter table public.player_accounts enable row level security;
alter table public.baths enable row level security;
alter table public.legacy_visits enable row level security;
alter table public.legacy_standings enable row level security;
alter table public.settings enable row level security;
alter table public.visits enable row level security;
alter table public.visit_players enable row level security;
alter table public.reviews enable row level security;
alter table public.standings enable row level security;
alter table public.visit_points enable row level security;

create policy "участники видны всем" on public.players for select using (true);
create policy "секретарь правит участников" on public.players for all to authenticated using (public.is_secretary()) with check (public.is_secretary());

create policy "свой аккаунт или секретарь" on public.player_accounts for select to authenticated
  using (auth_user = auth.uid() or public.is_secretary());
create policy "секретарь привязывает аккаунты" on public.player_accounts for update to authenticated
  using (public.is_secretary()) with check (public.is_secretary());

create policy "бани видны всем" on public.baths for select using (status <> 'rejected' or public.is_secretary());
create policy "участник предлагает новую баню" on public.baths for insert to authenticated
  with check (public.me() is not null and status = 'pending' and created_by = public.me());
create policy "секретарь правит бани" on public.baths for update to authenticated
  using (public.is_secretary()) with check (public.is_secretary());

create policy "остаток виден всем" on public.legacy_visits for select using (true);
create policy "остаток зачёта виден всем" on public.legacy_standings for select using (true);
create policy "настройки видны всем" on public.settings for select using (true);
create policy "таблица видна всем" on public.standings for select using (true);
create policy "очки походов — для участников лиги" on public.visit_points for select to authenticated using (public.me() is not null);

create policy "лента — для участников лиги" on public.visits for select to authenticated using (public.me() is not null);
create policy "участник отмечает поход" on public.visits for insert to authenticated
  with check (created_by = public.me() and status = 'pending' and moderated_by is null);
create policy "секретарь модерирует" on public.visits for update to authenticated
  using (public.is_secretary()) with check (public.is_secretary());
create policy "свой поход на модерации можно удалить" on public.visits for delete to authenticated
  using ((created_by = public.me() and status = 'pending') or public.is_secretary());

create policy "компания — для участников лиги" on public.visit_players for select to authenticated using (public.me() is not null);
create policy "автор похода добавляет компанию" on public.visit_players for insert to authenticated
  with check (exists (select 1 from public.visits v where v.id = visit_id and v.created_by = public.me() and v.status = 'pending'));
create policy "каждый сам подтверждает долгий поход" on public.visit_players for update to authenticated
  using (player_id = public.me() or public.is_secretary()) with check (player_id = public.me() or public.is_secretary());
create policy "автор или секретарь убирает из компании" on public.visit_players for delete to authenticated
  using (public.is_secretary() or exists (select 1 from public.visits v where v.id = visit_id and v.created_by = public.me() and v.status = 'pending'));

create policy "отзывы видны всем" on public.reviews for select using (true);
create policy "свой отзыв" on public.reviews for insert to authenticated with check (player_id = public.me());
create policy "свой отзыв правлю" on public.reviews for update to authenticated using (player_id = public.me()) with check (player_id = public.me());
create policy "свой отзыв или секретарь удаляет" on public.reviews for delete to authenticated using (player_id = public.me() or public.is_secretary());

grant select on public.bath_counts to anon, authenticated;
grant execute on function public.claim_nick(text) to authenticated;

-- ---------- фото с отметками времени ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('proofs', 'proofs', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic'])
on conflict (id) do nothing;

create policy "фото видят участники лиги" on storage.objects for select to authenticated
  using (bucket_id = 'proofs' and public.me() is not null);
create policy "фото кладут в свою папку" on storage.objects for insert to authenticated
  with check (bucket_id = 'proofs' and (storage.foldername(name))[1] = public.me()::text);
create policy "свои фото можно удалить" on storage.objects for delete to authenticated
  using (bucket_id = 'proofs' and ((storage.foldername(name))[1] = public.me()::text or public.is_secretary()));

-- ---------- права (в проекте выключена автоматическая выдача прав на новые таблицы) ----------
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant select on public.players, public.baths, public.legacy_visits, public.legacy_standings,
  public.settings, public.standings, public.reviews to anon, authenticated;
grant insert, update, delete on public.players to authenticated;
grant select, update on public.player_accounts to authenticated;
grant insert, update on public.baths to authenticated;
grant select, insert, update, delete on public.visits, public.visit_players to authenticated;
grant insert, update, delete on public.reviews to authenticated;
grant select on public.visit_points to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.me(), public.is_secretary() to anon, authenticated;
